---
- name: AUTO GENERATE FILES AND DIRECTORIES
  hosts: all
  connection: local
  gather_facts: false

  tasks:
    
    - name: DELETE DIRECTORIES PREVIOUSLY CREATED ON OS
      ansible.builtin.file:
        path: ./tmp
        state: absent